export const MOSTRAR_LISTA = 'MOSTRAR_LISTA';
export const VALIDAR_ERROR = 'VALIDAR_ERROR'
export const OBTENER_DATOS ='OBTENER_DATOS'
export const OCULTAR_FORM = 'OCULTAR_FORM'
export const MOSTRAR_SPINNER = 'MOSTRAR_SPINNER'
export const DIAS_RESERVA = 'DIAS_RESERVA'

